// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ByChanderZap/exile-tracker/models"
import "fmt"
import "time"

func SnapshotsPage(swe []models.SnapshotWithExtras, stringValue func(*string) string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.4.18/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"/static/htmx.min.js\"></script><link rel=\"icon\" type=\"image/x-icon\" href=\"/static/favicon.ico\"></head><body class=\"min-h-screen w-full bg-[#101014] text-white\" style=\"\n        background-image:\n          repeating-linear-gradient(0deg, rgba(255,255,255,0.04) 0, rgba(255,255,255,0.04) 1px, transparent 1px, transparent 40px),\n          repeating-linear-gradient(45deg, rgba(0,255,128,0.09) 0, rgba(0,255,128,0.09) 1px, transparent 1px, transparent 20px),\n          repeating-linear-gradient(-45deg, rgba(255,0,128,0.10) 0, rgba(255,0,128,0.10) 1px, transparent 1px, transparent 30px),\n          repeating-linear-gradient(90deg, rgba(255,255,255,0.03) 0, rgba(255,255,255,0.03) 1px, transparent 1px, transparent 80px),\n          radial-gradient(circle at 60% 40%, rgba(0,255,128,0.05) 0, transparent 60%);\n        background-size: 80px 80px, 40px 40px, 60px 60px, 80px 80px, 100% 100%;\n        background-position: 0 0, 0 0, 0 0, 40px 40px, center;\n      \"><div class=\"container mx-auto lg:py-8\"><div class=\"text-center mb-8\"><h1 class=\"text-3xl font-bold mb-2\">Exile Tracker</h1></div><div class=\"flex flex-col items-center\"><div class=\"flex flex-row gap-4 items-center justify-center mb-6\"><a href=\"#\" class=\"text-lg font-medium hover:text-pink-400 transition\">Accounts</a> <a href=\"#\" class=\"text-lg font-medium hover:text-pink-400 transition\">Characters</a> <a href=\"#\" class=\"text-lg font-medium hover:text-pink-400 transition\">Snapshots</a></div><h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%s Snapshots by %s", swe[0].CharacterName, swe[0].AccountName))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/templates/snapshots.templ`, Line: 44, Col: 89}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h2><!-- <label class=\"mb-1 text-sm text-gray-300\" for=\"search-accounts\">Search accounts</label> --><!-- <input --><!-- \tid=\"search-characters\" --><!-- \ttype=\"text\" --><!-- \tplaceholder=\"Search...\" --><!-- \tclass=\"input input-bordered w-64 text-black bg-transparent text-white\" --><!-- \thx-get={fmt.Sprintf(\"/accounts/%s/characters/search\", accountId)} --><!-- \thx-trigger=\"keyup changed delay:500ms\" --><!-- \thx-target=\"#characters-table\" --><!-- \thx-include=\"[name='q']\" --><!-- \tname=\"q\" --><!--        /> --></div><div class=\"flex flex-col gap-4 justify-center items-center bg-transparent md:pt-8\"><div id=\"characters-table\" class=\"w-full max-w-4xl mx-auto border border-gray-600 rounded-lg overflow-hidden backdrop-blur-sm\"><div class=\"flex font-bold bg-gray-400 bg-opacity-15\"><div class=\"flex-1 px-4 py-3 border-r border-gray-600\">ID</div><div class=\"flex-1 px-4 py-3 border-r border-gray-600\">PoB</div><div class=\"text-white flex-1 px-4 py-3 border-r border-gray-600\">Fetched time</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, data := range swe {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"flex hover:bg-gray-700/50 transition-colors border-b border-gray-600 last:border-b-0\"><div class=\"flex-1 px-4 py-3 border-r border-gray-600 text-white break-all\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.SnapshotData.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/templates/snapshots.templ`, Line: 77, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"flex-1 px-4 py-3 border-r border-gray-600 text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.SnapshotData.ExportString)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/templates/snapshots.templ`, Line: 80, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"flex-1 px-4 py-3 border-r border-gray-600 text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(time.Since(data.SnapshotData.CreatedAt).Truncate(time.Second))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/templates/snapshots.templ`, Line: 83, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
