root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  pre_cmd = ["templ generate", "goose -dir ./migrations sqlite3 ./data.db up"]
  cmd = "go build -o ./tmp/exile-tracker ./cmd"
  bin = "./tmp/exile-tracker"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_templ\\.go$"]
  delay = 1000
  log = "build-errors.log"
  

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
